name: dependabot automerge

on:
  pull_request:
    types:
      - labeled
    branches:
      - "updates"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.12.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
      - uses: actions/checkout@v2
        with:
          ref: "updates"
      - run: hub pull-request -m 'Update dependencies'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
