name: Auto-merge Pull Request

on:
  pull_request:
    types:
      - opened
    branches:
      - "deps/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.12.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
