name: Open Pull Request

on:
  push:
    branches:
      - updates

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: hub pull-request -m 'update dependencies'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
